name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed for actions like peaceiris/actions-gh-pages to push to a branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write # Grant GITHUB_TOKEN write permission to deploy to GitHub Pages
      id-token: write # For OpenID Connect (if needed, good practice)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
          publish_branch: gh-pages 